name: Deploy nessefy-backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into EC2_nessefy-backend
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2_nessefy-backend
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/ness-backend  # or wherever your code should live
          git pull origin main     # pull latest code
          sudo docker stop $(docker ps -aq) || true
          sudo docker rm $(docker ps -aq) || true
          sudo docker rmi -f $(docker images -aq) || true
          sudo docker system prune -a -f
          sudo apt clean
          sudo docker build -t nessefy-backend .
          sudo docker run -d --name nessefy-backend -p 5223:5223 nessefy-backend
        EOF
