name: Deploy to BAckend - EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nessefy-backend:latest .
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/nessefy-backend:latest

    - name: SSH and deploy
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/ness-backend
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nessefy-backend:latest
          sudo docker-compose up -d
        EOF
